language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: c1DniflMyAMWskwpyA5ZtcEIZ3u92SQHI361xHQO3zwx2pTXr2IpOK8MwxgF0XOKtHEmIsoflXYKIoubY84iD/l9jA+9yLsITqNlG4mjeJNvpjuiVyb+SgyfgE4u/MHZ/Z55ZmE1ImAmjN0ct8r/aJsPNGaeemPAohgGNrnWTSIDLNPoI6EfwfL4oRMCP8AzRmDL5YGQT35wLl+DUslvL37MyR8HH9SwaGmL5iiM3XvOY15EBXHj7lBfB/JSZtfH5gYZi0H5dU0E47MoL1u13kZZJaY2/pujr+6YmGeIqqNMVYGm9Rk+pSG4/qpj2h5dIa/SDUeRgnQyFTN1NbTyEDHk1yRheXtqhYMc1Oy/scRAkqmKR9GkdGCFP+x3VbaV1q+c93rt7H6zx/RnWfKOUtCImiR/EuKQhmxqfcpjM1eMAplLRDpDqLA4rEURMECUJYK7xI6lrZ8Lz+SzUSgWPIdb4HBPcl7rEte7LdU/Ubnz19c95SnzytKojyWxs/c6C4mT0myBimzM270m4mG14r/Dntm9EuKRfmedHN+jeyV3vYsBywyl67kL0UGH1e24Njou9ssX2pEomDJr6WVoGzJol7F7WJlMmK4KNaswk1xSNc+wGGlq75hz6h2E3iVfFUV5HzQlSwQDOoc02tKPOeuNV/VM9DVwCHW5U/SNgVg=
  app: https://shielded-shore-58631.herokuapp.com/
  on:
    repo: mikeramz86/roomie-node-capstone
